title: Zcoding4mer Blog
email: Zcoding4mer@outlook.com
author: Zcoding4mer
description: >-
  Hello World!
  I'm zcoding4mer, whose a junior front-end engineer.
  I will share someting i learned, about javascript and some other computer technologies.
url: "zcoding4mer.github.io"
github_username:  Zcoding4mer
permalink: /:categories/:slug

baidu_id: 9ed8e83d044bbcad101ac679a41a3269

plugins: 
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
